name: CI
on:
  push:
    branches:
      - main
      - dev
      - gh-pages
  pull_request:
jobs:
  Check_linting_test_and_build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REGISTERY_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: npx eslint src
    - name: Check if CookieMonsterShortcutsDev.js is built correctly
      run: |
        npx webpack -o ./tmp --env minimize
        if cmp <(head -n 2 dist/CookieMonsterShortcutsDev.js) <(head -n 2 tmp/CookieMonsterShortcutsDev.js); then
            echo '### SUCCESS: CookieMonsterShortcutsDev is built correctly! ###'
        else
            echo '### WARNING: CookieMonsterShortcutsDev.js does not seem to be correct. Make sure to run "npm run build-dev" after saving all your changes! ###'
            exit 1
        fi
    - name: Check if CookieMonsterShortcuts.js is built correctly
      if: github.ref == 'refs/heads/master'
      run: |
        npx webpack -o ./tmp --env minimize --env finalfile
        if cmp <(head -n 2 dist/CookieMonsterShortcuts.js) <(head -n 2 tmp/CookieMonsterShortcuts.js); then
            echo '### SUCCESS: CookieMonster is built correctly! ###'
        else
            echo '### WARNING: CookieMonsterShortcuts.js does not seem to be correct. Make sure to run "npm run build-final" after saving all your changes! ###'
            exit 1
        fi